=== petrul/misc/stories/compare_stories_test_webapp/src/test/resources/stories/story.dtd
<!ELEMENT alt (#PCDATA|text|ch)* >
<!ATTLIST alt copy-original CDATA #IMPLIED >
<!ATTLIST alt altid CDATA #REQUIRED >
<!ATTLIST alt ignore CDATA #IMPLIED >
<!ELEMENT alternatives ( alt+ ) >
<!ELEMENT categories ( category+, comment? ) >
<!ELEMENT category ( #PCDATA ) >
<!ELEMENT comment ( #PCDATA ) >
<!ELEMENT id ( #PCDATA ) >
<!ELEMENT vdmid ( #PCDATA ) >
<!ELEMENT original ( #PCDATA ) >



<!ATTLIST story ignore CDATA #IMPLIED >
<!ELEMENT ch ( #PCDATA ) >
<!ELEMENT insert (#PCDATA )>
<!ELEMENT text ( #PCDATA | ch )* >
<!ELEMENT main ( #PCDATA | insert )* >
<!ELEMENT insert-test (main, alternatives+) >
<!ELEMENT compare-test (alternatives+) >

<!ELEMENT story ( id?, vdmid?, original, comment?, categories, compare-test?, insert-test? ) >

=== petrul/misc/stories/stories.xml/028-quadruplets.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
	<id>28</id>
	<original>
		http://www.gulfnews.com/nation/General/10261440.html
		
		Dubai: A Sudanese woman gave birth to quadruplets at Al Wasl
		Hospital on Thursday morning, becoming the second person to do so in
		Dubai's recorded history, according to her family.
    </original>

	<categories>
		<category>deviation quantitative</category>
	</categories>

	<insert-test>

		<main>
			J'ai une voisine en bas de chez moi 
			qui a donné naissance à des <insert />
			il y a juste quelques jours. Elle a accouché prématurément, 
			elle disait être étonnée de les voir si petits.
		</main>

		<alternatives>
			<alt altid="1">quadruplés</alt>
			<alt altid="2">triplés</alt>
			<alt altid="3">jumeaux</alt>
		</alternatives>

	</insert-test>
</story>

=== petrul/misc/stories/stories.xml/poubelle/017-essence-prix-bas-pompe-fermee.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story ignore="yes">
    <id>17</id>
    <original>
        Aujourd'hui, je dois faire le plein de ma voiture. En chemin, je trouve une
        pompe à essence, le prix est vraiment bas, incroyable, incroyable, je m'arrête,
        je sors de la voiture... Pour constater que la pompe est fermée. Depuis 8 mois.
        C'est écrit en tout petit. VDM   
    </original>
    
    <comment>à travailler</comment>
    
    <categories>
    	<category>hypothèse</category>
    </categories>
    
    <insert-test>
    	<main>
    		Je dois faire le plein de ma voiture. En chemin, je trouve une
	        pompe à essence, le prix est vraiment bas, incroyable, incroyable, je m'arrête,
	        je sors de la voiture. <insert />... 
    	</main>
    	<alternatives>
    		<alt altid="1">En fait la pompe était fermée depuis 8 mois, 
    			c'était écrit en tout petit.</alt>
    		<alt altid="2">En fait j'avais simplement mal vu.</alt>
    	</alternatives>
    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/poubelle/001-000875-cinema-plein-tarif.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story ignore="yes">
    <id>1</id>
    <vdmid>875</vdmid>
    <original>je suis allé au cinéma, à la caisse la dame m'a fait payer plein tarif mais pas à mes potes</original>

    <comment>pas sûr si on garde cette histoire</comment>

    <categories>
        <category>déviation qualitative</category>
        <category>inéquité</category>
    </categories>

    <insert-test>
        <main>Je suis allé au cinéma avec mes amis : à la caisse la dame m'a fait payer 
            plein tarif <insert/>.
        </main>
        <alternatives>
            <alt altid="1">mais pas à mes amis</alt>
            <alt altid="2">et à mes amis aussi</alt>
        </alternatives>
    </insert-test>
    
    <compare-test>
        <alternatives>
            <alt altid="1">
                Je suis allé au cinéma avec mes amis : à la caisse la dame m'a fait payer plein tarif 
                mais pas à mes amis.
            </alt>

            <alt altid="2">
                Je suis allé au cinéma avec mes amis : à la caisse la dame m'a fait payer plein tarif 
                et à mes amis aussi.
            </alt>
        </alternatives>
    </compare-test>

</story>

=== petrul/misc/stories/stories.xml/009-nathalie-cousins-cabine-laragne.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>

    <id>9</id>

    <original>
        Adele me téléphone, et ne peut s'empêcher de me raconter qu'au moment
        d'entrer dans la cabine, elle entend "Nathalie". Elle se retourne,
        c'étaient des cousins qu'elle n'avait pas vus depuis 10 ans. C'était une
        sacrée coïncidence parce qu'ils ne voulaient pas du tout venir à
        Laragne. Ils passaient par là à cause des manifestations de routiers qui
        bloquaient l'autoroute. 
    </original>
    
    <comment>
    </comment>
    
    <categories>
        <category>coincidence</category>
        <category>remote encounter</category>
    </categories>
    
    <insert-test> 
        <main>
                J'étais en vacances à Stockholm et au moment d'entrer dans une
                cabine téléphonique, j'ai entendu quelqu'un m'appeler : je me suis retourné,
                c'était <insert/>.
        </main>

        <alternatives>
            <alt altid="1">mon frère que je n'avais pas vu depuis 10 ans</alt>
            <alt altid="2">des cousins que je n'avais pas vus depuis 10 ans</alt>
            <alt altid="3">des cousins que je n'avais pas vus depuis 1 an</alt>
        </alternatives>
        
    </insert-test>
    
    <compare-test>

        <alternatives>
            <alt altid="1">
                <text>
                    Ma soeur Adele est à Laragne et me téléphone: elle me raconte qu'au moment
                    d'entrer dans la cabine téléphonique, elle avait entendu quelqu'un l'appeler.
                    Elle s'est retourné, c'étaient <ch>des cousins qu'elle n'avait pas vus
                    depuis 10 ans</ch>.
    
                    En fait, ils ne voulaient pas du tout venir à
                    Laragne. Ils passaient par là à cause des manifestations de
                    routiers qui bloquaient l'autoroute.
                </text>
            </alt>
    
            <alt altid="2">
                <text>
                    Ma soeur Adele est à Laragne et me téléphone: elle me raconte qu'au moment
                    d'entrer dans la cabine téléphonique, elle avait entendu quelqu'un l'appeler.
                    Elle s'est retourné, c'étaient <ch>des cousins qu'elle n'avait pas vus depuis 2 mois.</ch>.
    
                    En fait, ils ne voulaient pas du tout venir à
                    Laragne. Ils passaient par là à cause des manifestations de
                    routiers qui bloquaient l'autoroute.
                </text>
            </alt>
    
            <alt altid="3">
                <text>
                    Ma soeur Adele est à Laragne et me téléphone: elle me raconte qu'au moment
                    d'entrer dans la cabine téléphonique, elle avait entendu quelqu'un l'appeler.
                    Elle s'est retourné, c'étaient <ch>des passants</ch>.
    
                    En fait, ils ne voulaient pas du tout venir à
                    Laragne. Ils passaient par là à cause des manifestations de
                    routiers qui bloquaient l'autoroute.
                </text>
            </alt>
    
        </alternatives>
    </compare-test>
</story>

=== petrul/misc/stories/stories.xml/012-double-suicide-baie-des-anges.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>12</id>
    <original>
        Surprise, suspense et perplexité pour les gendarmes maritimes de Nice et les
        policiers du commissariat d'Antibes, confrontés à une énigme peu banale : celle
        de la découverte dans la baie des Anges, dans l'après midi, des corps flottant
        entre deux eaux de deux femmes d'âge mûr aux élégantes tenues vestimentaires.
        
        Apparemment les deux noyades, voisines dans le temps ne se sont pas produites au
        même endroit, compte tenu des courants marins. Parmi les hypothèses, celle de
        passagères tombées ou poussées du pont d'un bateau de croisière. Aucune trace de
        coups n'a été décelée sur les deux corps. Ils n'ont séjourné dans l'eau que
        quelques heures. 
        
        En réalité, une extraordinaire coïncidence aurait poussé deux
        femmes d'âge similaire, mais ne se connaissant absolument pas, à choisir le même
        jour pour aller en pleine matinée se noyer presque simultanément au même endroit
        et en tenue élégante.
        
        C'est l'explication qui semble devoir être retenue par des
        enquêteurs plutôt sidérés. Dans le cas d'une des victimes, Michèle R.,
        domiciliée dans le Maryland aux Etats-Unis, sa soeur a indiqué qu'elle était
        très dépressive. Un promeneur l'aurait fugitivement entrevue au moment où elle
        entrait de son plein gré dans l'eau. Il aurait cru " au geste d'une originale ".
        Quant à la deuxième noyée, originaire de la région niçoise, elle aurait laissé à
        son domicile une lettre pour expliquer son geste.    
    </original>

    <comment></comment>

    <categories>
        <category>coincidence</category>
        <category>analogy</category>
    </categories>

    <insert-test>
        <main>
         Les policiers du comissariat d'Antibes ont découvert dans l'après midi 
         dans la baie des Anges les corps flottants de deux
         femmes aux élégantes tenues vestimentaires. Apparemment les deux
         noyades se sont passées à peu près en même temps. De plus, les deux femmes <insert/>.
        </main>
        <alternatives>
            <alt altid="1">avaient chacune un tatouage rouge représentant le dragon Tsuba-Kasai sur le bras droit</alt>
            <alt altid="2">avaient chacune un tatouage rouge sur le bras droit</alt>
            <alt altid="3">avaient chacune un tatouage sur le bras droit</alt>
        </alternatives>
    </insert-test>
    
</story>

=== petrul/misc/stories/stories.xml/poubelle/025-ex-meilleure-ami-mariage-meme-jour.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>25</id>
    <original>
        Aujourd'hui, je reçois des nouvelles de ma meilleure amie et de mon ex : un
        faire part de mariage... Coïncidence, ils se marient le même jour... VDM 
    </original>

    <comment>
    	à retravailler
    </comment>

    <categories>
    	<category>analogy</category>
    </categories>

    <insert-test>
    	<main>
	    	Je regardais dans l'album familial, c'est bizarre, ma mère et ma grandmère
	    	se sont mariées les deux le même jour, le 14 septembre, <insert /> ...
    	</main>
    	<alternatives>
    		<alt altid="1">
    			en plus ma grandmère a changé de nom de Triboulet en Ollagnier 
    			alors que ma mère, à l'invers, a changé son nom de jeune fille Ollagnier en Triboulet</alt>
			<alt altid="2">en plus elles portaient des robes de mariées faites par la même enseigne de tailleurs</alt>
    		<alt altid="3">en plus elles avaient le même âge</alt>
    	</alternatives>
    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/poubelle/026-eleve-branleur-feuille-perdue.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story ignore="yes">

	<id>26</id>

	<original>
		Aujourd'hui, j'ai mis 0 à un élève genre branleur, et une colle pour mensonge : il
		assurait m'avoir rendu un devoir à faire alors que je ne l'avais pas
		dans mon tas de copies. En fait si, elle avait glissé derrière mon
		bureau. Je vais devoir m'excuser demain. J'avais pourtant cherché
		partout.
    </original>

	<categories>
		<category>hypothèse</category>
	</categories>

	<insert-test>
		<main>
		</main>
		<alternatives>
			<alt altid="1"></alt>
		</alternatives>
	</insert-test>

</story>

=== petrul/misc/stories/stories.xml/027-plappeville.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
	<id>27</id>
	<original>
		Je t'ai parlé de M. C'est un gars au boulot, on a été dans le même
		bureau pendant un an et demi. Hier on discutait, il me parle de son
		service militaire. Il me dit "j'ai fais mon service dans un petit
		village, Pap... Pla... Plappeville". C'est marrant, on a passé plus
		d'un an dans le même bureau, et hier il me dit ça.
    </original>

	<categories>
		<category>coïncidence</category>
	</categories>

	<insert-test>
		<main>
			Mon collègue au boulot, on a été dans le même
			bureau pendant un moment. Hier on discutait, il me parle de son
			service militaire. Il me dit "j'ai fait mon service dans un petit
			village, Pap... Pla... Plappeville". 
			C'est mon village natal! 
			C'est marrant, on a passé <insert/> dans le même bureau, et hier il me dit ça.
		</main>
		<alternatives>
			<alt altid="1">deux ans</alt>
			<alt altid="2">un an</alt>
			<alt altid="3">un mois</alt>
		</alternatives>
	</insert-test>
</story>
