=== petrul/misc/stories/compare_stories_test_webapp/src/test/resources/stories/story.dtd
<!ELEMENT alt (#PCDATA|text|ch)* >
<!ATTLIST alt copy-original CDATA #IMPLIED >
<!ATTLIST alt altid CDATA #REQUIRED >
<!ATTLIST alt ignore CDATA #IMPLIED >
<!ELEMENT alternatives ( alt+ ) >
<!ELEMENT categories ( category+, comment? ) >
<!ELEMENT category ( #PCDATA ) >
<!ELEMENT comment ( #PCDATA ) >
<!ELEMENT id ( #PCDATA ) >
<!ELEMENT vdmid ( #PCDATA ) >
<!ELEMENT original ( #PCDATA ) >



<!ATTLIST story ignore CDATA #IMPLIED >
<!ELEMENT ch ( #PCDATA ) >
<!ELEMENT insert (#PCDATA )>
<!ELEMENT text ( #PCDATA | ch )* >
<!ELEMENT main ( #PCDATA | insert )* >
<!ELEMENT insert-test (main, alternatives+) >
<!ELEMENT compare-test (alternatives+) >

<!ELEMENT story ( id?, vdmid?, original, comment?, categories, compare-test?, insert-test? ) >

=== petrul/misc/stories/stories.xml/020-piece-10-centimes-par-terre.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>20</id>

    <original>
        Aujourd'hui, je vois une pièce de 10 centimes par terre dans ma chambre. J'ai la
        flemme de me baisser pour la ramasser, je la laisse donc où elle est. Ce midi,
        il me manque 10 centimes pour m'acheter un sandwich et personne pour me les
        avancer. J'ai faim. VDM
    </original>

	<categories>
		<category>analogy</category>
	</categories>

    <insert-test>
    	<main>
	    	Ce matin, je vois une pièce de 20 centimes par terre dans ma chambre. J'ai la
	        flemme de me baisser pour la ramasser, je la laisse donc où elle est. Ce midi,
	        je veux m'acheter un sandwich, je m'aperçois qu'il me manque <insert /> centimes  
	        et je ne trouve personne pour me les avancer.
        </main>

        <alternatives>
        	<alt altid="1">20</alt>
        	<alt altid="2">10</alt>
        	<alt altid="3">5</alt>
        </alternatives>
    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/poubelle/008-telephone-sonne-chez-les-duponts.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>8</id>

    <original>
        Tu sais quoi? J'arrivais, là. J'entends le téléphone sonner, je me dis vite!
        Mais je m'aperçois que c'est chez les Schweitzer. Et tu sais quoi, c'était Maman
        qui téléphonait chez les Schweitzer.
    </original>
    
    <comment>
        pas sur de le garder
        
        difficile à comprendre : compréhensions :
            "j'entre je vois Maman qui téléphone"
            "j'entends le voisin dire 'Ah, bonjour, madame X'"
    </comment>
    
    <categories>
        <category>coincidence</category>
    </categories>
    
    
    <insert-test>
        <main>
            J'arrivais à la maison. 
            J'entends le téléphone sonner à travers la porte, je me dis vite, il faut que je réponde! 
            Mais je m'aperçois que c'est chez les voisins, chez les Dupont. 

            Et tu sais quoi, c'était <insert/> qui téléphonait chez les Dupont.
        </main>
        <alternatives>
            <alt altid="1">Maman</alt>
            <alt altid="2">leur fille</alt>
            <alt altid="3">leur banquier</alt>
        </alternatives>
    </insert-test>
    
</story>

=== petrul/misc/stories/stories.xml/003-171819-patrick.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">

<story>
    <id>3</id>
    <vdmid>171819</vdmid>
    <original>à la machine à café, je parlais avec un collègue 
    de Bob l'Eponge et plus particulièrement de Patrick, l'étoile de mer. 
    A un moment, je lance "J'aime pas Patrick, il est trop con." 
    Mon chef de service passe, il s'appelle Patrick.</original>

    <comment>
    </comment>

    <categories>
        <category>emotional</category>
        <category>humour</category>
        
        <category>analogy</category>
    </categories>

    
    <insert-test>
        <main>à la machine à café, je parlais avec un collègue 
            de Bob l'Eponge et plus particulièrement de son meilleur ami, 
            Patrick, l'étoile de mer.
             
            A un moment, je lance "J'aime pas Patrick, l'étoile de mer, il est trop bête".

            A cet instant précis, mon chef de service passe, il s'appelle <insert/>.
        </main>

        <alternatives>
            <alt altid="1">Patrick Etoile</alt>
            <alt altid="2">Patrick</alt>
            <alt altid="3">Christophe</alt>
        </alternatives>

    </insert-test>


    <compare-test>
        <alternatives>
            <alt altid="1">
                à la machine à café, je parlais avec un collègue 
                    de Bob l'Eponge et plus particulièrement de Patrick, l'étoile de mer. 
                    A un moment, je lance "J'aime pas Patrick".
                    Mon chef de service passe, il s'appelle Patrick.
            </alt>
    
            <alt altid="2">
                à la machine à café, je parlais avec un collègue 
                    de Bob l'Eponge et plus particulièrement de Patrick, l'étoile de mer. 
                    A un moment, je lance "J'aime pas Patrick<ch></ch>". 
                    Mon chef de service passe, il s'appelle <ch>Patrice</ch>.
            </alt>
    
            <alt altid="3">
                à la machine à café, je parlais avec un collègue 
                    de Bob l'Eponge et plus particulièrement de Patrick, l'étoile de mer. 
                    A un moment, je lance "J'aime pas Patrick<ch></ch>".
                    Mon chef de service passe, il s'appelle <ch>Christophe</ch>.
            </alt>
        </alternatives>
    </compare-test>
</story>

=== petrul/misc/stories/stories.xml/018-peugeot-106-accident-gros-mercedes.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>18</id>
    <original>
        Aujourd'hui j'ai acheté ma petite peugeot 106, 2000 euros. Je l'avais essayée
        avant-hier, elle allait tip top. Je tourne la clé, démarre, sors de la propriété
        de l'ancien propriétaire de la voiture. Sa femme me rentre dedans avec sa grosse
        mercedes classe B... VDM
    </original>
    
    <categories>
    	<category>analogy</category>
    </categories>
    
    <insert-test>
    	<main>
	    	J'avais acheté une petite Peugeot 106 ColorLine, j'ai payé 2000 euros. Je l'avais essayée
	        la veille, elle roulait très bien. 
	        
	        J'ai tourné la clé, j'ai démarré, je suis sorti de la propriété
	        de l'ancien propriétaire de la voiture quand, venant de gauche sans regarder, 
	        c'est une autre <insert/> qui me rentre dedans ...
    	</main>
    	<alternatives>
    		<alt altid="1">Peugeot 106 ColorLine</alt>
    		<alt altid="2">Peugeot 106</alt>
    		<alt altid="3">Peugeot</alt>
    	</alternatives>
    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/029-nicole-kidman-divorce.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
	<id>29</id>
	<original>
		L’actrice hollywoodienne [Nicole Kidman], désormais mariée au chanteur country Keith
		Urban, est restée seule durant 6 années après ce divorce qu’elle
		qualifie de ‘très douloureux’.
    </original>
    
	<comment>
		google: le 9 déc 2008
			"Nicole Kidman" : 15 500 000
			"Kate Winslet" 	:  7 000 000
	</comment>
	
	<categories>
		<category>celebrity</category>
	</categories>

	<insert-test>
		<main>
			<insert /> s'est remariée après être restée seule durant six années 
			après son très douloureux divorce.
		</main>
		<alternatives>
			<alt altid="1">Nicole Kidman</alt>
			<alt altid="2">Kate Winslet</alt>
			<alt altid="3">Une connaissance à moi</alt>
		</alternatives>
	</insert-test>
</story>

=== petrul/misc/stories/stories.xml/015-j-ai-du-payer-amende-375.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>15</id>
    <original>
        Aujourd'hui j'ai dû payer 375 euros une amende vieille d'un an à cause du trésor
        public qui n'a pas envoyé les rappels a la bonne adresse, en plus j'avais 315
        euros sur mon compte et j'avais mon titre de transport sur moi quand je me suis
        pris l'amende . VDM  
    </original>
    
    <categories>
    	<category>analogy</category>
    </categories>
    
    <insert-test>
    	<main>
	    	J'ai dû payer 400 euros une amende vieille d'un an à cause du trésor
	        public qui n'a pas envoyé les rappels à la bonne adresse.
	         
	        Au moment du prélèvement, j'avais exactement <insert/> euros sur mon compte.
    	</main>
    	<alternatives>
    		<alt altid="1">400</alt>
    		<alt altid="2">401</alt>
    		<alt altid="3">419</alt>
    	</alternatives>
    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/024-vol-voiture-c_est_mon_copain.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>24</id>
    <original>
        Aujourd'hui, 2 semaines après le vol de ma voiture, la police m'apprend qu'une
        voiture qui a des chances d'être la mienne est en vente sur Internet. Ils me
        présentent l'annonce, le numéro de portable est celui d'un de mes voisins. Je le
        reconnais tout de suite, c'est aussi mon petit copain. VDM 
    </original>

    <categories>
    	<category>proximity</category>
    </categories>

    <insert-test>
    	<main>
	    	Deux semaines après le vol de ma voiture, la police m'apprend qu'une
	        voiture qui a des chances d'être la mienne est en vente sur Internet. Ils me
	        présentent l'annonce, le numéro de portable est identifié comme étant <insert/>.
    	</main>
    	<alternatives>
    		<alt altid="1">celui de mon collègue de bureau</alt>
    		<alt altid="2">celui d'un collègue de mon frère</alt>
    		<alt altid="3">celui de quelqu'un qui habite le même quartier</alt>
    	</alternatives>
    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/016-plaque-immatriculation-DCD.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>16</id>
    <original>
        Aujourd'hui, j'étais tout heureuse de troquer mon ancienne plaque
        d'immatriculation CKK pour une nouvelle. Je m'"appelle" maintenant DCD. Étant
        superstitieuse, je trouve ça moyen. VDM   
    </original>
    
    <categories>
    	<category>structure</category>
    </categories>
    
    <insert-test>
    	<main>
	    	Je suis allé récupérer la plaque d'immatriculation de ma toute nouvelle voiture;
	    	quand je regarde, mon numéro, c'est <insert/> .
    	</main>
    	<alternatives>
    		<alt altid="1">999 NNN 91</alt>
    		<alt altid="2">253 NNN 91</alt>
    		<alt altid="3">253 UPV 91</alt>
    	</alternatives>
    </insert-test>

</story>
