=== petrul/misc/stories/compare_stories_test_webapp/src/test/resources/stories/story.dtd
<!ELEMENT alt (#PCDATA|text|ch)* >
<!ATTLIST alt copy-original CDATA #IMPLIED >
<!ATTLIST alt altid CDATA #REQUIRED >
<!ATTLIST alt ignore CDATA #IMPLIED >
<!ELEMENT alternatives ( alt+ ) >
<!ELEMENT categories ( category+, comment? ) >
<!ELEMENT category ( #PCDATA ) >
<!ELEMENT comment ( #PCDATA ) >
<!ELEMENT id ( #PCDATA ) >
<!ELEMENT vdmid ( #PCDATA ) >
<!ELEMENT original ( #PCDATA ) >



<!ATTLIST story ignore CDATA #IMPLIED >
<!ELEMENT ch ( #PCDATA ) >
<!ELEMENT insert (#PCDATA )>
<!ELEMENT text ( #PCDATA | ch )* >
<!ELEMENT main ( #PCDATA | insert )* >
<!ELEMENT insert-test (main, alternatives+) >
<!ELEMENT compare-test (alternatives+) >

<!ELEMENT story ( id?, vdmid?, original, comment?, categories, compare-test?, insert-test? ) >

=== petrul/misc/stories/stories.xml/021-sfr-offre-trop-tard.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>21</id>
    <original>
        Aujourd'hui, cela fait 1 an que je dois changer de portable chez SFR. Je me
        décide enfin à y aller même s'il faut que je "banque" car pas assez de points
        carrés rouges. Portable acheté à 13h15. Message reçu de SFR à 14h12 : "Changez
        de mobile, SFR vous offre 15 000 points carrés rouges." VDM
    </original>
    
    <categories>
    	<category>temporal proximity</category>
    </categories>
    
    <insert-test>
    	<main>
	   		Cela fait un an que je dois changer de portable chez SFR. Je me
	        décide enfin à y aller même s'il faut que je paye une partie car je n'ai pas assez 
	        de points carrés rouges. J'ai acheté le portable à 13h00. 
	        <insert /> je reçois un message de SFR : 
	        "Changez de mobile, SFR vous offre 15 000 points carrés rouges."
    	</main>
    	<alternatives>
    		<alt altid="1">A 13h10</alt>
    		<alt altid="2">A 14h00</alt>
    		<alt altid="3">Deux semaines plus tard</alt>
    	</alternatives>
    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/002-161488-gifle.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>2</id>
    <vdmid>161488</vdmid>
    <original>
        je marche tranquillement dans la rue quand un parfait inconnu s'arrête devant moi, 
        me considère et me met une gifle phénoménale avant de continuer sa route.
    </original>

    <comment>à mettre en relation avec les blagues: le premier jour, le deuxième, le troisième</comment>
    
    <categories>
        <category>déviation qualitative</category>
        <category>humour</category>
    </categories>

   <insert-test>
        <main>Je marche tranquillement dans la rue quand un parfait inconnu s'arrête devant moi, 
            me regarde et <insert/> avant de continuer sa route.</main>
        <alternatives>
            <alt altid="1">me met une gifle phénoménale</alt>
            <alt altid="2">me met une gifle</alt>
            <alt altid="3">me demande l'heure</alt>
        </alternatives>
   </insert-test>
    
    <compare-test>
        <alternatives>
            <alt copy-original="yes" altid="1"></alt>
            <alt altid="2">
                je marche tranquillement dans la rue quand un parfait inconnu s'arrête devant moi, 
                        me considère et me <ch>regarde</ch> avant de continuer sa route.
            </alt>
            <alt altid="3">
                je marche tranquillement dans la rue quand un parfait inconnu me met une gifle.
            </alt>
            <alt altid="4">
                je marche tranquillement dans la rue quand <ch>mon compagnon de marche</ch> s'arrête devant moi, 
                me considère et me met une gifle phénoménale avant de continuer <ch>la</ch> route.
            </alt>
        </alternatives>
   </compare-test>

</story>

=== petrul/misc/stories/stories.xml/023-chances-pigeon-se-soulage-mon-oeuil.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>23</id>
    <original>
        Aujourd'hui, je me demande quelle était la probabilité pour qu'en me couchant au
        soleil dans l'herbe, un oiseau se soulage pile dans mon œil droit au seul moment
        où je l'ouvrais... Une sur des millions ? Alors on peut dire que j'ai beaucoup
        de chance. Ou pas... VDM 
    </original>
    
    <categories>
    	<category></category>
    </categories>
    
    <insert-test>
    	<main>
	    	J'étais couché dans l'herbe sous les arbres 
	    	un après-midi d'automne, 
	    	quand une feuille morte s'est posée pile <insert />... 
    	</main>

    	<alternatives>
    		<alt altid="1">sur mon nez</alt>
    		<alt altid="2">sur mon visage</alt>
    		<alt altid="3">sur mon corps</alt>
    	</alternatives>

    </insert-test>
</story>

=== petrul/misc/stories/stories.xml/poubelle/011-piece-monaie-poubelle.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story ignore="yes">
    <id>11</id>
    <original>
        Je jouais avec la pièce [sur le bureau] comme ça, et puis elle est tombée en
        plein milieu [de la poubelle vide]. Elle a fait comme ça [elle a roulé dans la
        poubelle, fait le geste], et puis elle est s'est arrêtée là.
    </original>
    
    <comment>pas sur de la garder</comment>
    
    <categories>
        <category>coincidence</category>
    </categories>
    
    <alternatives>
        <alt altid="1">
            <text>
                Je jouais avec une pièce sur le bureau. Elle a roulé sur le bureau,
                après elle est tombé dans la poubelle vide, elle a roulé encore à l'intérieur
                de la poubelle et puis elle est s'est arrêtée <ch>en plein milieu</ch>.
            </text>
        </alt>
        <alt altid="2">
            <text>
                Je jouais avec une pièce sur le bureau. Elle a roulé sur le bureau,
                après elle est tombé dans la poubelle vide, elle a roulé encore à l'intérieur
                de la poubelle et puis elle est s'est arrêtée<ch></ch>.
            </text>
        </alt>
    </alternatives>
</story>

=== petrul/misc/stories/compare_stories_test_webapp/src/test/resources/stories/007-saisie-drogues.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>7</id>
    <original></original>
    
    <categories>
        <category>déviation quantitative</category>
    </categories>
    
    <insert-test>
        <main>La Police d'Amiens a effectué mercredi une saisie
                <insert/> d'héroïne au numéro 13 de la rue Fafet.
       </main>
       
        <alternatives>
            <alt altid="1">d'un kilo</alt>
            <alt altid="2">de 5,7 kilos</alt>
            <alt altid="3">de 17 kilos</alt>
            <alt altid="4">de plus de 200 kilos</alt>
        </alternatives>
    </insert-test>
    
    <compare-test>
        <alternatives>
            <alt altid="1">
                Aujourd'hui la Police de St. Malo a effectué une saisie d' 
                <ch>un kilo</ch> de cocaïne.
            </alt>
            <alt altid="2">
                Aujourd'hui la Police de St. Malo a effectué une saisie de 
                <ch>2 tonnes</ch> de cocaïne.
            </alt>
        </alternatives>
    </compare-test>

</story>

=== petrul/misc/stories/stories.xml/013-population-4444.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>13</id>
    <original>C'est marrant, je tombe là-dessus, ‘la ville de Saint-Chéron compte 4444 habitants’.</original>

    <comment>si je remplace avec 'la ville de Sète compte 77777 habitants ?'</comment>

    <categories>
        <category>Remarkable structure</category>
    </categories>

    <insert-test>
         <main>C'est marrant, j'ai trouvé ça sur Internet: la ville de St-Chéron compte <insert /> habitants.</main>
         <alternatives>
            <alt altid="1">4444</alt>
            <alt altid="2">4000</alt>
            <alt altid="3">3856</alt>
         </alternatives>
    </insert-test>


    <compare-test>
        <alternatives>
            <alt altid="1">
                <text>C'est marrant, je tombe là-dessus, ‘la ville de Saint-Chéron 
                compte 4444 habitants’.</text>
            </alt>
            <alt altid="2">
                <text>C'est marrant, je tombe là-dessus, ‘la ville de Saint-Chéron 
                compte 1234 habitants’.</text>
            </alt>
            <alt altid="3">
                <text>C'est marrant, je tombe là-dessus, ‘la ville de Saint-Chéron 
                compte 7183 habitants’.</text>
            </alt>
        </alternatives>
    </compare-test>

</story>

=== petrul/misc/stories/stories.xml/010-babysitter.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>10</id>


    <original>
        L. me raconte que l'après-midi même, elle a rencontré a entendu qu'on
        l'appelait: c'étaient des jeunes filles dont elle avait été babysitter pendant
        deux ans 8 ans auparavant. Elles ont échangé leurs adresses. Ca lui a fait super
        plaisir.
    </original>


    <comment></comment>


    <categories>
        <category>coincidence</category>
        <category>remote encounter</category>
    </categories>


    <insert-test>
        <main>
            Je passais dans une rue en plein milieu de Paris 
            quand j'ai entendu quelqu'un m'appeler: 
            c'était un gars <insert/> quand il était gamin.
            Nous avons échangé nos adresses. Ca m'a fait super plaisir.
        </main>

        <alternatives>
            <alt altid="1">que j'ai babysitté pendant 2 ans</alt>
            <alt altid="2">que j'ai babysitté pendant 2 mois</alt>
            <alt altid="3">que j'ai babysitté quelques soirs</alt>
        </alternatives>
    </insert-test>


    <compare-test>
        <alternatives>
            <alt altid="1">
                <text>
                    Cet après-midi même, Louise a entendu qu'on l'appelait: c'étaient deux jeunes filles
                    <ch>dont elle avait été babysitter pendant 2 ans, 8 ans auparavant</ch>. Elles ont
                    échangé leurs adresses. Ca lui a fait super plaisir.
                </text>
            </alt>
            <alt altid="2">
                <text>
                    Cet après-midi même, Louise a entendu qu'on l'appelait: c'étaient deux jeunes filles
                    <ch>qu'elle avait rencontrées 8 ans auparavant</ch>. Elles ont
                    échangé leurs adresses. Ca lui a fait super plaisir.
                </text>
            </alt>
            <alt altid="3">
                <text>
                    Cet après-midi même, Louise a entendu qu'on l'appelait: c'étaient deux jeunes filles
                    <ch>dont elle avait été babysitter pendant 3 jours, 8 ans auparavant</ch>. Elles ont
                    échangé leurs adresses. Ca lui a fait super plaisir.
                </text>
            </alt>
    
        </alternatives>
    </compare-test>


</story>

=== petrul/misc/stories/stories.xml/022-euromillion-grille.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="story2html.xsl"?>
<!DOCTYPE story SYSTEM "story.dtd">
<story>
    <id>22</id>
    <original>
        Aujourd'hui, je vais au bureau de tabac de mon village, je tends mon ticket
        Euromillions et on m'annonce, forcément, que je n'ai aucun gain. "Par contre" me
        dit la buraliste "et je n'ai jamais vu ça, votre grille est celle de la semaine
        dernière ! A une semaine près, c'est bête ça". Gros moment de détresse. VDM
    </original>
    
    <categories>
    	<category>temporal proximity</category>
    </categories>
    
    <insert-test>
    	<main>
    		Je vais au bureau de tabac de mon village, je tends mon ticket
	        Euromillions et on m'annonce, forcément, que je n'ai aucun gain. "Par contre" me
	        dit la buraliste "et je n'ai jamais vu ça, votre grille est exactement <insert/> !".
        </main>
        
        <alternatives>
        	<alt altid="1">celle de la semaine dernière</alt>
        	<alt altid="2">celle d'il y a deux semaines</alt>
        	<alt altid="3">celle d'il y a cinq mois</alt>
        </alternatives>
    </insert-test>
</story>
